kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claimarb
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-storage 
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

